from .exception_base import ExceptionBase


class FaultNotFoundException(ExceptionBase):
    pass
